Repository tangle-network/tangle, pull requests merged in 2024-01, with the labels that each got.

#387 feat: Add tests for distribution logic
  node/src/distributions/mainnet.rs
Labels: Waiting for CI

#396 Fix Wrapping Message Method
  node/src/chainspec/testnet.rs
  node/src/distributions/develop.rs
  pallets/claims/src/lib.rs
Labels: needs review 👓

#398 feat : set address prefixes
  node/Cargo.toml
  node/src/chainspec/mainnet.rs
  node/src/chainspec/testnet.rs
  primitives/src/lib.rs
  runtime/mainnet/src/lib.rs
  runtime/testnet/src/lib.rs
Labels: needs review 👓, DO NOT MERGE 🛑

#394 bugfix: Fix claims pallet
  node/src/chainspec/mainnet.rs
  node/src/chainspec/testnet.rs
  node/src/distributions/develop.rs
  node/src/distributions/mainnet.rs
  pallets/claims/src/lib.rs
  pallets/claims/src/tests.rs
  pallets/claims/src/utils/ethereum_address.rs
Labels: approved ✅

#384 feat: update benchmark build and add claims pallet benchmarks
  .maintain/frame-weights-template.hbs
  Cargo.lock
  node/Cargo.toml
  node/src/benchmarking.rs
  node/src/command.rs
  node/src/main.rs
  node/src/service.rs
  pallets/claims/src/lib.rs
  pallets/claims/src/mock.rs
  pallets/claims/src/weights.rs
  pallets/dkg/Cargo.toml
  pallets/dkg/src/benchmarking.rs
  pallets/dkg/src/lib.rs
  pallets/dkg/src/mock.rs
  pallets/dkg/src/tests.rs
  pallets/jobs/Cargo.toml
  pallets/jobs/src/benchmarking.rs
  pallets/roles/Cargo.toml
  primitives/src/lib.rs
  relayer-gadget/Cargo.toml
  relayer-gadget/cli/Cargo.toml
  runtime/mainnet/Cargo.toml
  runtime/mainnet/src/frontier_evm.rs
  runtime/mainnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/src/lib.rs
Labels: needs review 👓

#397 feat : add jobs pallet rpc calls
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/rpc/mod.rs
  pallets/jobs/rpc/Cargo.toml
  pallets/jobs/rpc/runtime-api/Cargo.toml
  pallets/jobs/rpc/runtime-api/src/lib.rs
  pallets/jobs/rpc/src/lib.rs
  pallets/jobs/src/rpc.rs
  primitives/Cargo.toml
  primitives/src/jobs/mod.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/src/lib.rs
Labels: needs review 👓

#401 Store Role key while creating profile
  pallets/jobs/src/functions.rs
  pallets/jobs/src/lib.rs
  pallets/jobs/src/mock.rs
  pallets/roles/src/impls.rs
  pallets/roles/src/lib.rs
  pallets/roles/src/profile.rs
  pallets/roles/src/tests.rs
  precompiles/jobs/src/mock.rs
  primitives/src/roles/traits.rs
Labels: needs review 👓

#412 chore : Update testnet artifacts
  .github/workflows/publish-release-binary.yml
  Cargo.lock
  Cargo.toml
  chainspecs/testnet/tangle-standalone.json
  chainspecs/testnet/tangle-testnet.json
  node/src/chainspec/testnet.rs
  node/src/command.rs
  node/src/testnet_fixtures.rs
  node/src/utils.rs
  runtime/testnet/src/lib.rs
  types/src/interfaces/augment-api-errors.ts
  types/src/interfaces/augment-api-events.ts
  types/src/interfaces/augment-api-query.ts
  types/src/interfaces/augment-api-tx.ts
  types/src/interfaces/lookup.ts
  types/src/interfaces/registry.ts
  types/src/interfaces/types-lookup.ts
  types/src/metadata/metadata.json
  types/src/metadata/static-latest.ts
Labels: Waiting for CI
