Repository tangle-network/tangle, pull requests merged in 2024-12, with the labels that each got.

#841 fix!: make tangle-subxt no-std compatible again
  .github/workflows/check-subxt.yml
  Cargo.lock
  tangle-subxt/Cargo.toml
  tangle-subxt/README.md
  tangle-subxt/src/tangle_testnet_runtime.rs
Labels: task ✔️, Breaking Change

#856 feat: Multi Asset Delegation pallet fuzzing
  .gitignore
  Cargo.lock
  Cargo.toml
  flake.nix
  pallets/multi-asset-delegation/Cargo.toml
  pallets/multi-asset-delegation/fuzzer/Cargo.toml
  pallets/multi-asset-delegation/fuzzer/call.rs
  pallets/multi-asset-delegation/src/functions/evm.rs
  pallets/multi-asset-delegation/src/functions/operator.rs
  pallets/multi-asset-delegation/src/lib.rs
  pallets/multi-asset-delegation/src/mock.rs
  pallets/multi-asset-delegation/src/tests/operator.rs
  pallets/multi-asset-delegation/src/types/rewards.rs
Labels: testing 🛠️, task ✔️

#858 feat: MAD Precompile fuzzing
  Cargo.lock
  Cargo.toml
  precompiles/multi-asset-delegation/Cargo.toml
  precompiles/multi-asset-delegation/fuzzer/Cargo.toml
  precompiles/multi-asset-delegation/fuzzer/call.rs
  precompiles/multi-asset-delegation/src/lib.rs
  precompiles/multi-asset-delegation/src/mock.rs
  precompiles/multi-asset-delegation/src/tests.rs
  taplo.toml
Labels: testing 🛠️

#859 chore!: fix MAD Precompile function names
  precompiles/multi-asset-delegation/src/lib.rs
Labels: difficulty: starter 🏁, task ✔️, Breaking Change
