Repository tangle-network/tangle, pull requests merged in 2025-02, with the labels that each got.

#910 chore: bump subxt to 0.39.0
  Cargo.lock
  Cargo.toml
  tangle-subxt/Cargo.toml
  tangle-subxt/README.md
  tangle-subxt/metadata/tangle-testnet-runtime.scale
  tangle-subxt/src/tangle_testnet_runtime.rs
Labels: Breaking Change

#926 chore(types): Upgrade Yarn and Migrate Types to Tangle Network
  .gitignore
  types/.yarnrc.yml
  types/package-lock.json
  types/package.json
  types/yarn.lock
Labels: needs review 👓

#932 chore: `tangle-subxt` 0.12.0
  tangle-subxt/README.md
  tangle-subxt/metadata/tangle-testnet-runtime.scale
  tangle-subxt/src/tangle_testnet_runtime.rs
Labels: Breaking Change

#936 feat: retain type information in `Field`s
  Cargo.lock
  primitives/src/services/field.rs
  tangle-subxt/Cargo.toml
  tangle-subxt/README.md
  tangle-subxt/metadata/tangle-testnet-runtime.scale
  tangle-subxt/src/field_ext.rs
  tangle-subxt/src/lib.rs
  tangle-subxt/src/tangle_testnet_runtime.rs
Labels: feature ➕, Breaking Change

#937 chore: bump version to 1.2.10
  Cargo.lock
  Cargo.toml
  runtime/mainnet/src/lib.rs
  runtime/testnet/src/lib.rs
Labels: Breaking Change

#939 fix(types): Update Substrate Types, Use Modern Yarn on Release CI
  .github/workflows/publish-types.yml
  types/src/interfaces/augment-api-tx.ts
  types/src/interfaces/lookup.ts
  types/src/interfaces/types-lookup.ts
  types/src/metadata.json
  types/tsconfig.json
Labels: needs review 👓
